import Head from "next/head";
import Footer from "../src/components/Footer";
import HeroSection from "../src/components/HeroSection";
import Issue from "../src/components/Issue";
import Mission from "../src/components/Mission";
import NatGeoTv from "../src/components/NatGeoTv";
import Navbar from "../src/components/Navbar";
import Photography from "../src/components/Photography";
import Podcast from "../src/components/Podcast";
import TravelSection from "../src/components/TravelSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="w-full">
        <Navbar />
      </header>
      <main className="w-full">
        <HeroSection />
        <div className="h-24 bg-white"></div>
        <NatGeoTv />
        <TravelSection />
        <Podcast />
        <div className="h-24 bg-white"></div>
        <Photography />
        <Issue />
        <Mission />
      </main>

    <footer>
    <div className=" text-white relative px-4 py-8 md:p-8 grid place-content-center">
      <div className="relative z-10 space-y-8 text-center">
        <h1 className="uppercase font-semibold tracking-widest text-2xl md:text-4xl">
        THE BEST OF NATIONAL GEOGRAPHIC DELIVERED TO YOUR INBOX
        </h1>
        <p className="text-lg font-base">
        Sign up for more inspiring photos, stories, and special offers from National Geographic.
        </p>
        <a
          href="#"
          className="nav__button inline-block px-6 py-4 text-black uppercase w-full md:w-2/5"
        >
          <span className="base absolute inset-0 bg-custom-yellow"></span>
          <span
            className="bg inset-0"
            style={{
              backgroundColor: "#fff",
            }}
          ></span>
          <span className="relative z-10 font-medium tracking-widest text-base">
            Sign up
          </span>
        </a>
      </div>

      <div className="absolute inset-0 z-0">
        <span
          className="background-image block h-full"
          style={{
            backgroundImage: "url(/images/footer-top.webp)",
            backgroundPosition: "left center",
            opacity: 0.7,
          }}
        ></span>
      </div>
    </div>
    <Footer />
    </footer>

    </div>
  );
}
